### ISSUE TITLE
Fórmula de área del rombo

### ISSUE THREAD

**Issue by Alijoestar** [OpenFormulaApp/OpenFormulaDBs#1]
Segmento **AB-CD** en lugar de _AB-BD_ 
![image](https://user-images.githubusercontent.com/80805429/114227442-9f9dbd80-993a-11eb-9ff9-e0c8458ebf76.png)

**Comment by UriMtzF** [comment]
Corregido en commit [5b17d8c](https://github.com/OpenFormulaApp/OpenFormulaDBs/commit/5b17d8c731cf841922b7b366267dd7ddd523a8c2).
Si las fórmulas no se muestran, actualiza la página con `shift + F5`.
